services:
  bot:
    build: .
    container_name: nomi_assistant
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VOSK_MODEL_PATH=/app/models/vosk-model
      - DB_PATH=/app/data/app.db
    volumes:
      - ./data:/app/data
      - ./models/vosk-small-en:/app/models/vosk-model:ro

